name: .NET Core

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2.3.4
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1.8.0
      with:
        dotnet-version: '5.0.100'
    - name: Install dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --configuration Release --no-restore
    - name: Test
      run: dotnet test --no-restore --verbosity normal
    - name: Publish
      if: ${{ github.event_name != 'pull_request' }}
      run: dotnet nuget push ./AsyncBinaryExtensions/bin/Release/*.nupkg -k "${{secrets.NUGET}}" --skip-duplicate -s https://api.nuget.org/v3/index.json
